from .floors.basement import WAREHOUSE_ZONE_NAME

LOG_MIN_PERIOD = 1.0

NAV_WAREHOUSE_ZONE_NAME = WAREHOUSE_ZONE_NAME

TIME_FOR_FIRST_CALL = 60.0 * 2
TIME_BEETWEEN_NOTIFICATIONS_PACKAGE_ARRIVED = 60.0 * 3

# go to floor
TIME_TO_WAIT_AFTER_SELECTION_ELEVATOR = 3.0
