from .floors.basement import WAREHOUSE_ZONE_NAME

NAV_WAREHOUSE_ZONE_NAME = WAREHOUSE_ZONE_NAME

TIME_TO_WAIT_AFTER_BUTTON_PRESS = 0.1
TIME_BEETWEEN_NOTIFICATIONS_PACKAGE_ARRIVED = 10.0

# go to floor
TIME_TO_WAIT_AFTER_SELECTION_ELEVATOR = 3.0
