NAV_WAREHOUSE_ZONE_NAME = 'warehouse'

TIME_TO_WAIT_AFTER_BUTTON_PRESS = 0.1
TIME_BEETWEEN_NOTIFICATIONS_PACKAGE_ARRIVED = 10.0
TIME_PASSING_THROUGH_DOOR = 25.0

MAX_RETRY_COUNTER_REQUEST_FOR_HELP = 3
TIMEOUT_REQUEST_FOR_HELP = 1.0

CHEST_LISTENER_PATHS = ['/chest_button']

# go to floor
TIME_TO_WAIT_AFTER_SELECTION_ELEVATOR = 3.0
